# .github/workflows/manual-job.yaml
name: Manual Command Runner

on:
 workflow_dispatch:

env: 
  IMAGE_REPOSITORY: krish290490/helloworld
  TAG: feature-{{ github.run_number }}

jobs:
  BuildDocker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v3


      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}


      - name: Build and Push Docker Image
        run: |
           docker build -t $IMAGE_REPOSITORY:feature-${{ github.run_number }} .
           docker push $IMAGE_REPOSITORY:feature-${{ github.run_number }}
