# .github/workflows/manual-job.yaml
name: Manual Command Runner

on:
 workflow_dispatch:

jobs:
  BuildDocker:
    name: Docker build
    runs-on: ubuntu-latest

    steps:
      - name: Run specified commands
        run: |
          ls -lart
          pwd
          cd ASIA-APP && docker build -t localbuild:apache .
